server:
  port: 9000

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

local:
  database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:fb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
#  jpa:
#    generate-ddl: true
#    show-sql: true
#
#    defer-datasource-initialization: true

