language: java

jdk:
  - openjdk20

addons:
  sonarcloud:
    organization: "final-project-1"
    token:
      secure: "7cf7015bc8d2fef84c549a169100f1ab3645e322"

script:
  - mvn -f social-network-api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=final-project-1_facebook-app
  - mvn -f social-network-api/ clean test jacoco:report coveralls:report