language: java

jdk:
  - openjdk20

addons:
  sonarcloud:
    organization: "final-project-1"
    token:
      secure: "1ed5ec07d8fff7456fd2de639bc7420944d99b6d"

script:
  - mvn -f social-network-api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=final-project-1_facebook-app
  - mvn -f social-network-api/ clean test jacoco:report coveralls:report