language: java

jdk:
  - openjdk20

addons:
  sonarcloud:
    organization: "final-project-1"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn -f social_network_api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=final-project-1_facebook-app
  - mvn -f social_network_api/ clean test jacoco:report coveralls:report