language: java

jdk:
  - openjdk20

addons:
  sonarcloud:
    organization: "fp1-2"
    token:
     secure: "7e6a741d3977f1f8648ae69ceca78bc05t74d92a"

script:
  - mvn -f social-network-api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=FP1-2_facebook
  - mvn -f social-network-api/ clean test jacoco:report coveralls:report