language: java

jdk:
  - openjdk20

addons:
  sonarcloud:
    organization: "FP1-2"
    token: ${SONAR_TOKEN}

script:
  - mvn -f social-network-api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=FP1-2_facebook
  - mvn -f social-network-api/ clean test jacoco:report coveralls:report